//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Falcon.Core.Builder {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GearBuilderResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GearBuilderResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Falcon.Core.Builder.GearBuilderResources", typeof(GearBuilderResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to addBackpack &quot;{0}&quot;;.
        /// </summary>
        internal static string AddBackpackCommand {
            get {
                return ResourceManager.GetString("AddBackpackCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to addGoggles &quot;{0}&quot;;.
        /// </summary>
        internal static string AddGogglesCommand {
            get {
                return ResourceManager.GetString("AddGogglesCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to addHeadgear &quot;{0}&quot;;.
        /// </summary>
        internal static string AddHeadgearCommand {
            get {
                return ResourceManager.GetString("AddHeadgearCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to addItemCargoGlobal [&quot;{0}&quot;,{1}];.
        /// </summary>
        internal static string AddItemsCommand {
            get {
                return ResourceManager.GetString("AddItemsCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to addPrimaryWeaponItem &quot;{0}&quot;;.
        /// </summary>
        internal static string AddPrimaryWeaponItemCommand {
            get {
                return ResourceManager.GetString("AddPrimaryWeaponItemCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to addSecondaryWeaponItem &quot;{0}&quot;;.
        /// </summary>
        internal static string AddSecondaryWeaponItemCommand {
            get {
                return ResourceManager.GetString("AddSecondaryWeaponItemCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to addHandgunItem &quot;{0}&quot;;.
        /// </summary>
        internal static string AddSidearmItemCommand {
            get {
                return ResourceManager.GetString("AddSidearmItemCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to forceAddUniform &quot;{0}&quot;;.
        /// </summary>
        internal static string AddUniformCommand {
            get {
                return ResourceManager.GetString("AddUniformCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to addVest &quot;{0}&quot;;.
        /// </summary>
        internal static string AddVestCommand {
            get {
                return ResourceManager.GetString("AddVestCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to addWeapon &quot;{0}&quot;;.
        /// </summary>
        internal static string AddWeaponCommand {
            get {
                return ResourceManager.GetString("AddWeaponCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to linkItem &quot;{0}&quot;;.
        /// </summary>
        internal static string AssignItemCommand {
            get {
                return ResourceManager.GetString("AssignItemCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to clearAllItemsFromBackpack _unit;.
        /// </summary>
        internal static string ClearBackpackCommand {
            get {
                return ResourceManager.GetString("ClearBackpackCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Generated by Falcon on: {0}.
        /// </summary>
        internal static string GeneratedByComment {
            get {
                return ResourceManager.GetString("GeneratedByComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (backpackContainer _unit).
        /// </summary>
        internal static string UnitBackpackFunc {
            get {
                return ResourceManager.GetString("UnitBackpackFunc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _unit.
        /// </summary>
        internal static string UnitFunc {
            get {
                return ResourceManager.GetString("UnitFunc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to };.
        /// </summary>
        internal static string UnitgearCaseClosing {
            get {
                return ResourceManager.GetString("UnitgearCaseClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to case &quot;{0}&quot;: {{.
        /// </summary>
        internal static string UnitgearCaseOpening {
            get {
                return ResourceManager.GetString("UnitgearCaseOpening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //--unitgear.sqf--.
        /// </summary>
        internal static string UnitgearFileNameLine {
            get {
                return ResourceManager.GetString("UnitgearFileNameLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to removeGoggles _unit;
        ///removeAllWeapons _unit;
        ///removeAllAssignedItems _unit;
        ///removeAllItemsWithMagazines _unit;
        ///removeHeadgear _unit;
        ///removeAllContainers _unit;.
        /// </summary>
        internal static string UnitgearItemRemoval {
            get {
                return ResourceManager.GetString("UnitgearItemRemoval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to };.
        /// </summary>
        internal static string UnitgearLoadoutSwitchClosing {
            get {
                return ResourceManager.GetString("UnitgearLoadoutSwitchClosing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to switch (_type) do {.
        /// </summary>
        internal static string UnitgearLoadoutSwitchOpening {
            get {
                return ResourceManager.GetString("UnitgearLoadoutSwitchOpening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to private [&quot;_unit&quot;, &quot;_type&quot;];
        ///_unit = _this select 0;
        ///_type = _this select 1;
        ///if (!local _unit) exitWith {};.
        /// </summary>
        internal static string UnitgearPrefixArrayInit {
            get {
                return ResourceManager.GetString("UnitgearPrefixArrayInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _unit setVariable [&quot;BIS_enableRandomization&quot;, false];.
        /// </summary>
        internal static string UnitgearRandomizationDisabling {
            get {
                return ResourceManager.GetString("UnitgearRandomizationDisabling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (uniformContainer _unit).
        /// </summary>
        internal static string UnitUniformFunc {
            get {
                return ResourceManager.GetString("UnitUniformFunc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (vestContainer _unit).
        /// </summary>
        internal static string UnitVestFunc {
            get {
                return ResourceManager.GetString("UnitVestFunc", resourceCulture);
            }
        }
    }
}
